import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import "typeface-lato";
import Providers from './components/providers'
import SiteHeader from './components/SiteHeader'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tearrings',
  description: 'Generated by create next app',
  icons: {
     icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SiteHeader/>
          <Navbar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
